### ISSUE TITLE
TypeScript output doesn't put quotes around snake-case property names

### ISSUE THREAD

**Issue by TylerEich** [jsontypedef/json-typedef-codegen#23]
```json
{
  "properties": {
    "snake-case": { "type": "boolean" }
  }
}
```

Generates the following TypeScript output:

```typescript
// Code generated by jtd-codegen for TypeScript v0.2.0

export interface Blah {
  snake-case: boolean;
}
```

`snake-case` has to be wrapped in a string to be a valid type definition.

`echo '{"properties":{"snake-case": {"type":"boolean"}}}' | jtd-codegen - --typescript-out ~ --root-name "blah"`

**Comment by ucarion** [comment]
What version of `jtd-codegen` are you using (`jtd-codegen --version`)? This should be addressed in the latest release.

However, looking more carefully it does seem that the Homebrew release of `jtd-codegen` is not up to date with the latest release. Either way, I'll keep this ticket open until that's addressed.

**Comment by ucarion** [comment]
For context, this is the code generated I get from 0.4.1 of jtd-codegen:

```ts
// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Blah {
  "snake-case": boolean;
}
```

**Comment by TylerEich** [comment]
Ahhh yeah, I'm using Homebrew and I'm on `jtd-codegen 0.3.0`. Thanks for confirming! I'm looking forward to the fix being pushed to Homebrew.

**Comment by TylerEich** [comment]
@ucarion Any news here?

**Comment by ucarion** [comment]
This was addressed in https://github.com/jsontypedef/homebrew-jsontypedef/commit/d99e4669a89ad71f682951b410d6aa0b4126e805. Sorry for the delay here!
