### ISSUE TITLE
generate multiple types at once

### ISSUE THREAD

**Issue by advancedtw** [jsontypedef/json-typedef-codegen#24]
can we generate types from a directory of jtd.json files ? 
for example let's say I have these two files in my schema directory "user.jtd.json" and "company.jtd.json". 
can I generate ts types for both at once ? something like "jtd-codegen schemas/**/*.jtd.json --typescript-out src/types.ts"

**Comment by ucarion** [comment]
No, this isn't possible. You will need to either combine the schemas into a single schema, or you will need to generate a separate set of types for each file.

**Comment by MauScheff** [comment]
I find this a bit unpractical for large projects, where you may want to split your schemas (definitions) into multiple files. It adds complexity on the compiler to find and bundle / cross reference multiple schemas, but it would be great from a developer experience standpoint.
