### ISSUE TITLE
NPM packaging request

### ISSUE THREAD

**Issue by delaneyj** [jsontypedef/json-typedef-codegen#26]
Right now in a CI/CD respect the current workflow of downloading separate release binaries is setting off red flags for usage.  It would be great if there was some NPM package similar to https://github.com/timostamm/protobuf-ts/tree/master/packages/protoc where its downloading the proper binaries and setting on path.  It also means the binaries are pasted through our artifactory instance to track versioning when related to generated containers.

**Comment by ucarion** [comment]
I can't commit to doing this work. The relevant effort required to set up a release process for such an NPM package is too great.

A package like the one proposed can be implemented by any third party, so I don't think this is a need-to-have in `jtd-codegen` per se.
