### ISSUE TITLE
Output to stdout as json

### ISSUE THREAD

**Issue by delaneyj** [jsontypedef/json-typedef-codegen#27]
I want to be able to use jtd-codegen as an part of a larger generator, right now you are dumping to a folder (at least in TS as an index.ts) which is not ideal.  Would like to have something like

`jtd-codegen --typescript-out test req.json --log-format json --export-to-logs`

Which would no write out files but the output would contain the results ala
```json
{
  "TypeScript": {
    "out_dir": "test",
    "root_name": "Req",
    "definition_names": {},
    "output":"// Code generated by jtd-codegen for TypeScript v0.2.1\n\nexport type..."
}
```

**Comment by ucarion** [comment]
While I agree this could be useful for many folks, I can't commit to doing this work, as it would require a pretty considerable change to how the generator works. That said, I am open to reviewing a PR that attempts to implement this.

**Comment by ucarion** [comment]
Closing for triage purposes.
