### ISSUE TITLE
Keep order of attributes in JTD schema

### ISSUE THREAD

**Issue by julien-c** [jsontypedef/json-typedef-codegen#34]
Hi, thanks for this great project @ucarion 🙏 

Is there any way to keep the order of attributes definition from the JTD file, and not reorder them?

**Comment by ucarion** [comment]
I'm afraid not. The code generated is alphabetized so that output is stable
as long as the schema is semantically identical.

The ordering of keys isn't meaningful in JSON or in JTD, and so the code
generator disregards such information in order to have fewer spurious diffs
in its output.
