### ISSUE TITLE
[Suggestion] Release/publish jtd-codegen to npm

### ISSUE THREAD

**Issue by 100terres** [jsontypedef/json-typedef-codegen#36]
Hi,

First, thank you for your work with this project! :tada: 

I'm using the `jtd-codegen` CLI on one of my project to generate some TypeScript types from a JTD schema generated using a custom Serializer writing in Ruby. The serializers are used to pass some data to the frontend written in TypeScript. The `jtd-codegen` is used in a CI environment to ensure consistency between the frontend and the backend.

It would be really useful to be able to install the codegen using a package manager like npm/yarn, because it is what a lot of people are using to install their dependencies and it would allow us to add simple script commands in a `package.json` to easily run the codegen in any environment.

```json5
{
  "dependencies": {
    "jtd-codegen": "x.x.x",
    // any other deps
  },
  "scripts": {
    "generate-typings": "jtd-codegen --typescript-out path/to/schema.json path/to/types/folder"
  }
}
```
and then in any environment we could simply run:
```sh
npm install
npm run generate-typings
```

Here are some documentation/examples on how to achieve this :slightly_smiling_face: 
- https://github.com/cloudflare/binary-install
- https://github.com/cloudflare/binary-install/tree/master/packages/binary-install-example
- https://dev.to/woubuc/publishing-a-rust-binary-on-npm-1lgf

If you need any help do not hesitate to ask me. I can help and propose a PR if you are open to it. :slightly_smiling_face: 

Thank you again for this project! :tada:

**Comment by ucarion** [comment]
Thank you for reaching out!

As I understand it, there are workarounds to this: for instance, you can install jtd-codegen as usual before running scripts. Moreover, there's nothing that requires jtd-codegen in particular to maintain such an NPM package itself, as far as I can tell. Such a package could be maintained "out-of-tree" by others, so to speak?

If both of these are the case, then it's quite unlikely that this will be implemented here.

**Comment by 100terres** [comment]
Hi @ucarion :slightly_smiling_face:,

> you can install jtd-codegen as usual before running scripts

Of course we can install it as usual, but it might not be ideal when we have a large team, because when there is an update to the version everyone need to do it manually. Compare to if it was on npm when there is an update we just need to change the `package.json` with the new version and run `npm install`.

>  there's nothing that requires jtd-codegen in particular to maintain such an NPM package itself, as far as I can tell. Such a package could be maintained "out-of-tree" by others

Technically it could, but I guess that such a package in a separate repository managed by the community might become out-of-date if not properly maintained, because the maintainer would have to be made aware when there is new version of the codegen and then release it on npm. If the setup is done within this repository it could be integrated directly in the release mechanism of the repo and we could avoid the situation where the package become out-of-date.

Let me know what you think :slightly_smiling_face:

**Comment by 100terres** [comment]
An other reason to have a packge on npm (and/or other package managers) would be to automate the update of this dependency on other projects using tools like [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) or [renovate](https://github.com/renovatebot/renovate), which automatically open a PR on a project when a new version of a dependency is available on npm (and others)

**Comment by ucarion** [comment]
> Technically it could, but I guess that such a package in a separate repository managed by the community might become out-of-date if not properly maintained, because the maintainer would have to be made aware when there is new version of the codegen and then release it on npm. If the setup is done within this repository it could be integrated directly in the release mechanism of the repo and we could avoid the situation where the package become out-of-date.

I agree that it's easier to guarantee that things stay in sync if this were done in-tree. But that guarantee can still be established out-of-tree (GitHub has APIs that let you listen for new releases). 

Given that it would add to the maintenance burden of this project to add support for this, and that we can always change our mind later to _add_ this support (we can't do the same for _removing_ this support), I would be inclined to take a wait-and-see approach here. For instance, can we see if someone could build such a package, and get value from such a package, before reconsidering adding this in-tree?

Keep in mind, in all of this, that JavaScript's is not the only package manager out there; in deciding on a policy for handling such requests, one consideration is that Python, Java, Go, etc. all have similar versions of this ask. We'd need to decide how to handle a corresponding request for those languages. I believe the policy I've laid out here -- "as long as it can be done out-of-tree, then start there" -- gives us opportunity to make the right decision.
