### ISSUE TITLE
Using `json-typedef-codegen` as a library instead of a binary?

### ISSUE THREAD

**Issue by whereistejas** [jsontypedef/json-typedef-codegen#37]
Hi,
This is more like a feature-request or Q&A issue.

I was wondering if it possible to use this project as a dependency in another crate?

By the way, great work here!

**Comment by ucarion** [comment]
Only the CLI interface is supported. This is to simplify the story around packaging, releasing, and maintaining this tool. The fact that it's written in Rust is, at least for now, an internal detail that doesn't imply support for usage as a Rust library.
