### ISSUE TITLE
cant generate types from this jsonld schema

### ISSUE THREAD

**Issue by albjeremias** [jsontypedef/json-typedef-codegen#62]
i clone this repo: https://github.com/redaktor/ActivityPubSchema

and did: 
`jtd-codegen type/Accept.json --typescript-out ts/`

and I got
```
Error: Failed to parse input as JSON

Caused by:
unknown field `$id`, expected one of `definitions`, `nullable`, `ref`, `type`, `enum`, `elements`, `properties`, `optionalProperties`, `additionalProperties`, `values`, `discriminator`, `mapping`, `metadata` at line 2 column 8
```

**Comment by ucarion** [comment]
These are JSON Schema documents, not JSON Typedef. I'm afraid jtd-codegen cannot help you here; jtd-codegen only can generate code from JSON Typedef documents.

**Comment by albjeremias** [comment]
damn, and is it possible to convert schema do typedef? or maybe i can do it from the schema...
