### ISSUE TITLE
json schema codegen

### ISSUE THREAD

**Issue by moander** [jsontypedef/json-typedef-codegen#9]
I suggest adding `--json-schema-out` to the codegen. What do you guys think?

**Comment by ucarion** [comment]
This is a neat idea! One challenge, however, is that JSON Schema isn't really a programming language. Which means that most of the infrastructure within `jtd-codegen` won't work for JSON Schema.

For your use-case, would it be acceptable if there were some separate `jtd-to-json-schema` tool with this functionality? Do you need or strongly prefer this functionality to exist within `jtd-codegen`?

**Comment by ucarion** [comment]
Just for triage purposes, I'm closing this ticket. Please feel free to re-open this ticket if you'd like to discuss this further.
